Document: ixgbe
Title: Debian ixgbe Manual
Author: <insert document author here>
Abstract: This manual describes what ixgbe is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ixgbe/ixgbe.sgml.gz

Format: postscript
Files: /usr/share/doc/ixgbe/ixgbe.ps.gz

Format: text
Files: /usr/share/doc/ixgbe/ixgbe.text.gz

Format: HTML
Index: /usr/share/doc/ixgbe/html/index.html
Files: /usr/share/doc/ixgbe/html/*.html
